using System.Collections.Generic;
using System.Linq;
using LBGDBMetadata.Extensions;

namespace LBGDBMetadata.LaunchBox
{
    public static class Region
    {
        public const string None = "";
        public const string Asia = "Asia";
        public const string Australia = "Australia";
        public const string Brazil = "Brazil";
        public const string Canada = "Canada";
        public const string China = "China";
        public const string Europe = "Europe";
        public const string Finland = "Finland";
        public const string France = "France";
        public const string Germany = "Germany";
        public const string Greece = "Greece";
        public const string Holland = "Holland";
        public const string HongKong = "Hong Kong";
        public const string Italy = "Italy";
        public const string Japan = "Japan";
        public const string Korea = "Korea";
        public const string NorthAmerica = "North America";
        public const string Norway = "Norway";
        public const string Oceania = "Oceania";
        public const string Russia = "Russia";
        public const string SouthAmerica = "South America";
        public const string Spain = "Spain";
        public const string Sweden = "Sweden";
        public const string Thailand = "Thailand";
        public const string TheNetherlands = "The Netherlands";
        public const string UnitedKingdom = "United Kingdom";
        public const string UnitedStates = "United States";
        public const string World = "World";

        public static List<string> GetRegions(this string region)
        {
            List<string> regionList = new List<string>();
            if (!string.IsNullOrWhiteSpace(region))
            {
                regionList = region.Split(',').Select(item => item.Sanitize()).Where(item => !string.IsNullOrWhiteSpace(item)).Distinct().ToList();
            }

            return regionList;
        }

        public static Dictionary<string, int> GetRegionPriorityList(this string region)
        {
            Dictionary<string, int> regionPriorityList = new Dictionary<string, int>();
            if (string.IsNullOrWhiteSpace(region))
            {
                GetRegionPriority("canada", regionPriorityList);
                GetRegionPriority("usa", regionPriorityList);
            }
            else
            {
                var splitRegions = region.Split(',').Select(item => item.Sanitize()).Where(item => !string.IsNullOrWhiteSpace(item)).Distinct();
                foreach (var splitRegion in splitRegions)
                {
                    GetRegionPriority(splitRegion, regionPriorityList);
                }
            }
            
            return regionPriorityList;
        }
        
        private static void GetRegionPriority(string region, Dictionary<string, int> regionPriorityList)
        {
            if (RegionList.TryGetValue(region, out var regionInfo))
            {
                if (regionPriorityList.ContainsKey(regionInfo.RegionName))
                {
                    return;
                }

                regionPriorityList.Add(regionInfo.RegionName, regionPriorityList.Count);
                if (regionInfo.ParentRegion != null)
                {
                    GetRegionPriority(regionInfo.ParentRegion, regionPriorityList);
                }
            }
            else
            {
                if (!regionPriorityList.ContainsKey(region))
                {
                    regionPriorityList.Add(region, regionPriorityList.Count);
                }
                if (!regionPriorityList.ContainsKey(None))
                {
                    regionPriorityList.Add(None, regionPriorityList.Count);
                }
            }
        }

        private static readonly Dictionary<string, RegionInfo> RegionList = new Dictionary<string, RegionInfo>
        {
            //{"NA",new RegionInfo("Namibia","africa")},
            //{"AF",new RegionInfo("Afghanistan","asia")},
            //{"SA",new RegionInfo("Saudi Arabia","asia")},
            //{"AS",new RegionInfo("American Samoa","oceania")},
            {"holland", new RegionInfo(Holland, "europe")},
            {"korea", new RegionInfo(Korea, "asia")},
            {"russia", new RegionInfo(Russia, "europe")},
            {"unitedkingdom", new RegionInfo(UnitedKingdom, "europe")},
            {"unitedstates", new RegionInfo(UnitedStates, "northamerica")},
            {"", new RegionInfo(None, null)},
            {"dz", new RegionInfo("Algeria","africa")},
            {"ao", new RegionInfo("Angola","africa")},
            {"bj", new RegionInfo("Benin","africa")},
            {"bw", new RegionInfo("Botswana","africa")},
            {"io", new RegionInfo("British Indian Ocean Territory","africa")},
            {"bf", new RegionInfo("Burkina Faso","africa")},
            {"bi", new RegionInfo("Burundi","africa")},
            {"cv", new RegionInfo("Cabo Verde","africa")},
            {"cm", new RegionInfo("Cameroon","africa")},
            {"cf", new RegionInfo("Central African Republic","africa")},
            {"td", new RegionInfo("Chad","africa")},
            {"km", new RegionInfo("Comoros","africa")},
            {"cg", new RegionInfo("Congo","africa")},
            {"cd", new RegionInfo("Congo, Democratic Republic of the","africa")},
            {"ci", new RegionInfo("Côte d'Ivoire","africa")},
            {"dj", new RegionInfo("Djibouti","africa")},
            {"eg", new RegionInfo("Egypt","africa")},
            {"gq", new RegionInfo("Equatorial Guinea","africa")},
            {"er", new RegionInfo("Eritrea","africa")},
            {"sz", new RegionInfo("Eswatini","africa")},
            {"et", new RegionInfo("Ethiopia","africa")},
            {"tf", new RegionInfo("French Southern Territories","africa")},
            {"ga", new RegionInfo("Gabon","africa")},
            {"gm", new RegionInfo("Gambia","africa")},
            {"gh", new RegionInfo("Ghana","africa")},
            {"gn", new RegionInfo("Guinea","africa")},
            {"gw", new RegionInfo("Guinea-Bissau","africa")},
            {"ke", new RegionInfo("Kenya","africa")},
            {"ls", new RegionInfo("Lesotho","africa")},
            {"lr", new RegionInfo("Liberia","africa")},
            {"ly", new RegionInfo("Libya","africa")},
            {"mg", new RegionInfo("Madagascar","africa")},
            {"mw", new RegionInfo("Malawi","africa")},
            {"ml", new RegionInfo("Mali","africa")},
            {"mr", new RegionInfo("Mauritania","africa")},
            {"mu", new RegionInfo("Mauritius","africa")},
            {"yt", new RegionInfo("Mayotte","africa")},
            {"ma", new RegionInfo("Morocco","africa")},
            {"mz", new RegionInfo("Mozambique","africa")},
            {"ne", new RegionInfo("Niger","africa")},
            {"ng", new RegionInfo("Nigeria","africa")},
            {"re", new RegionInfo("Réunion","africa")},
            {"rw", new RegionInfo("Rwanda","africa")},
            {"sh", new RegionInfo("Saint Helena, Ascension and Tristan da Cunha","africa")},
            {"st", new RegionInfo("Sao Tome and Principe","africa")},
            {"sn", new RegionInfo("Senegal","africa")},
            {"sc", new RegionInfo("Seychelles","africa")},
            {"sl", new RegionInfo("Sierra Leone","africa")},
            {"so", new RegionInfo("Somalia","africa")},
            {"za", new RegionInfo("South Africa","africa")},
            {"ss", new RegionInfo("South Sudan","africa")},
            {"sd", new RegionInfo("Sudan","africa")},
            {"tz", new RegionInfo("Tanzania, United Republic of","africa")},
            {"tg", new RegionInfo("Togo","africa")},
            {"tn", new RegionInfo("Tunisia","africa")},
            {"ug", new RegionInfo("Uganda","africa")},
            {"eh", new RegionInfo("Western Sahara","africa")},
            {"zm", new RegionInfo("Zambia","africa")},
            {"zw", new RegionInfo("Zimbabwe","africa")},
            {"aq", new RegionInfo("Antarctica","antarctica")},
            {"am", new RegionInfo("Armenia","asia")},
            {"az", new RegionInfo("Azerbaijan","asia")},
            {"bh", new RegionInfo("Bahrain","asia")},
            {"bd", new RegionInfo("Bangladesh","asia")},
            {"bt", new RegionInfo("Bhutan","asia")},
            {"bn", new RegionInfo("Brunei Darussalam","asia")},
            {"kh", new RegionInfo("Cambodia","asia")},
            {"cn", new RegionInfo(China,"asia")},
            {"cy", new RegionInfo("Cyprus","asia")},
            {"ge", new RegionInfo("Georgia","asia")},
            {"hk", new RegionInfo(HongKong,"asia")},
            {"in", new RegionInfo("India","asia")},
            {"id", new RegionInfo("Indonesia","asia")},
            {"ir", new RegionInfo("Iran (Islamic Republic of)","asia")},
            {"iq", new RegionInfo("Iraq","asia")},
            {"il", new RegionInfo("Israel","asia")},
            {"jp", new RegionInfo(Japan,"asia")},
            {"jo", new RegionInfo("Jordan","asia")},
            {"kz", new RegionInfo("Kazakhstan","asia")},
            {"kp", new RegionInfo(Korea,"asia")},
            {"kr", new RegionInfo(Korea,"asia")},
            {"kw", new RegionInfo("Kuwait","asia")},
            {"kg", new RegionInfo("Kyrgyzstan","asia")},
            {"la", new RegionInfo("Lao People's Democratic Republic","asia")},
            {"lb", new RegionInfo("Lebanon","asia")},
            {"mo", new RegionInfo("Macao","asia")},
            {"my", new RegionInfo("Malaysia","asia")},
            {"mv", new RegionInfo("Maldives","asia")},
            {"mn", new RegionInfo("Mongolia","asia")},
            {"mm", new RegionInfo("Myanmar","asia")},
            {"np", new RegionInfo("Nepal","asia")},
            {"om", new RegionInfo("Oman","asia")},
            {"pk", new RegionInfo("Pakistan","asia")},
            {"ps", new RegionInfo("Palestine, State of","asia")},
            {"ph", new RegionInfo("Philippines","asia")},
            {"qa", new RegionInfo("Qatar","asia")},
            {"sg", new RegionInfo("Singapore","asia")},
            {"lk", new RegionInfo("Sri Lanka","asia")},
            {"sy", new RegionInfo("Syrian Arab Republic","asia")},
            {"tw", new RegionInfo("Taiwan, Province of China","asia")},
            {"tj", new RegionInfo("Tajikistan","asia")},
            {"th", new RegionInfo(Thailand,"asia")},
            {"tl", new RegionInfo("Timor-Leste","asia")},
            {"tr", new RegionInfo("Turkey","asia")},
            {"tm", new RegionInfo("Turkmenistan","asia")},
            {"ae", new RegionInfo("United Arab Emirates","asia")},
            {"uz", new RegionInfo("Uzbekistan","asia")},
            {"vn", new RegionInfo("Viet Nam","asia")},
            {"ye", new RegionInfo("Yemen","asia")},
            {"ax", new RegionInfo("Åland Islands","europe")},
            {"al", new RegionInfo("Albania","europe")},
            {"ad", new RegionInfo("Andorra","europe")},
            {"at", new RegionInfo("Austria","europe")},
            {"by", new RegionInfo("Belarus","europe")},
            {"be", new RegionInfo("Belgium","europe")},
            {"ba", new RegionInfo("Bosnia and Herzegovina","europe")},
            {"bg", new RegionInfo("Bulgaria","europe")},
            {"hr", new RegionInfo("Croatia","europe")},
            {"cz", new RegionInfo("Czechia","europe")},
            {"dk", new RegionInfo("Denmark","europe")},
            {"ee", new RegionInfo("Estonia","europe")},
            {"fo", new RegionInfo("Faroe Islands","europe")},
            {"fi", new RegionInfo(Finland,"europe")},
            {"fr", new RegionInfo(France,"europe")},
            {"de", new RegionInfo(Germany,"europe")},
            {"gi", new RegionInfo("Gibraltar","europe")},
            {"gr", new RegionInfo(Greece,"europe")},
            {"gg", new RegionInfo("Guernsey","europe")},
            {"va", new RegionInfo("Holy See","europe")},
            {"hu", new RegionInfo("Hungary","europe")},
            {"is", new RegionInfo("Iceland","europe")},
            {"ie", new RegionInfo("Ireland","europe")},
            {"im", new RegionInfo("Isle of Man","europe")},
            {"it", new RegionInfo(Italy,"europe")},
            {"je", new RegionInfo("Jersey","europe")},
            {"lv", new RegionInfo("Latvia","europe")},
            {"li", new RegionInfo("Liechtenstein","europe")},
            {"lt", new RegionInfo("Lithuania","europe")},
            {"lu", new RegionInfo("Luxembourg","europe")},
            {"mt", new RegionInfo("Malta","europe")},
            {"md", new RegionInfo("Moldova, Republic of","europe")},
            {"mc", new RegionInfo("Monaco","europe")},
            {"me", new RegionInfo("Montenegro","europe")},
            {"nl", new RegionInfo(TheNetherlands,"europe")},
            {"mk", new RegionInfo("North Macedonia","europe")},
            {"no", new RegionInfo(Norway,"europe")},
            {"pl", new RegionInfo("Poland","europe")},
            {"pt", new RegionInfo("Portugal","europe")},
            {"ro", new RegionInfo("Romania","europe")},
            {"ru", new RegionInfo(Russia,"europe")},
            {"sm", new RegionInfo("San Marino","europe")},
            {"rs", new RegionInfo("Serbia","europe")},
            {"sk", new RegionInfo("Slovakia","europe")},
            {"si", new RegionInfo("Slovenia","europe")},
            {"es", new RegionInfo(Spain,"europe")},
            {"sj", new RegionInfo("Svalbard and Jan Mayen","europe")},
            {"se", new RegionInfo(Sweden,"europe")},
            {"ch", new RegionInfo("Switzerland","europe")},
            {"ua", new RegionInfo("Ukraine","europe")},
            {"gb", new RegionInfo(UnitedKingdom,"europe")},
            {"vg", new RegionInfo("Virgin Islands (British)","northamerica")},
            {"ai", new RegionInfo("Anguilla","northamerica")},
            {"ag", new RegionInfo("Antigua and Barbuda","northamerica")},
            {"aw", new RegionInfo("Aruba","northamerica")},
            {"bs", new RegionInfo("Bahamas","northamerica")},
            {"bb", new RegionInfo("Barbados","northamerica")},
            {"bz", new RegionInfo("Belize","northamerica")},
            {"bm", new RegionInfo("Bermuda","northamerica")},
            {"bq", new RegionInfo("Bonaire, Sint Eustatius and Saba","northamerica")},
            {"ca", new RegionInfo(Canada,"northamerica")},
            {"ky", new RegionInfo("Cayman Islands","northamerica")},
            {"cr", new RegionInfo("Costa Rica","northamerica")},
            {"cu", new RegionInfo("Cuba","northamerica")},
            {"cw", new RegionInfo("Curaçao","northamerica")},
            {"dm", new RegionInfo("Dominica","northamerica")},
            {"do", new RegionInfo("Dominican Republic","northamerica")},
            {"sv", new RegionInfo("El Salvador","northamerica")},
            {"gl", new RegionInfo("Greenland","northamerica")},
            {"gd", new RegionInfo("Grenada","northamerica")},
            {"gp", new RegionInfo("Guadeloupe","northamerica")},
            {"gt", new RegionInfo("Guatemala","northamerica")},
            {"ht", new RegionInfo("Haiti","northamerica")},
            {"hn", new RegionInfo("Honduras","northamerica")},
            {"jm", new RegionInfo("Jamaica","northamerica")},
            {"mq", new RegionInfo("Martinique","northamerica")},
            {"mx", new RegionInfo("Mexico","northamerica")},
            {"ms", new RegionInfo("Montserrat","northamerica")},
            {"ni", new RegionInfo("Nicaragua","northamerica")},
            {"pa", new RegionInfo("Panama","northamerica")},
            {"pr", new RegionInfo("Puerto Rico","northamerica")},
            {"bl", new RegionInfo("Saint Barthélemy","northamerica")},
            {"kn", new RegionInfo("Saint Kitts and Nevis","northamerica")},
            {"lc", new RegionInfo("Saint Lucia","northamerica")},
            {"mf", new RegionInfo("Saint Martin (French part)","northamerica")},
            {"pm", new RegionInfo("Saint Pierre and Miquelon","northamerica")},
            {"vc", new RegionInfo("Saint Vincent and the Grenadines","northamerica")},
            {"sx", new RegionInfo("Sint Maarten (Dutch part)","northamerica")},
            {"tt", new RegionInfo("Trinidad and Tobago","northamerica")},
            {"tc", new RegionInfo("Turks and Caicos Islands","northamerica")},
            {"us", new RegionInfo(UnitedStates,"northamerica")},
            {"vi", new RegionInfo("Virgin Islands (U.S.)","northamerica")},
            {"au", new RegionInfo(Australia,"oceania")},
            {"cx", new RegionInfo("Christmas Island","oceania")},
            {"cc", new RegionInfo("Cocos (Keeling) Islands","oceania")},
            {"ck", new RegionInfo("Cook Islands","oceania")},
            {"fj", new RegionInfo("Fiji","oceania")},
            {"pf", new RegionInfo("French Polynesia","oceania")},
            {"gu", new RegionInfo("Guam","oceania")},
            {"hm", new RegionInfo("Heard Island and McDonald Islands","oceania")},
            {"ki", new RegionInfo("Kiribati","oceania")},
            {"mh", new RegionInfo("Marshall Islands","oceania")},
            {"fm", new RegionInfo("Micronesia (Federated States of)","oceania")},
            {"nr", new RegionInfo("Nauru","oceania")},
            {"nc", new RegionInfo("New Caledonia","oceania")},
            {"nz", new RegionInfo("New Zealand","oceania")},
            {"nu", new RegionInfo("Niue","oceania")},
            {"nf", new RegionInfo("Norfolk Island","oceania")},
            {"mp", new RegionInfo("Northern Mariana Islands","oceania")},
            {"pw", new RegionInfo("Palau","oceania")},
            {"pg", new RegionInfo("Papua New Guinea","oceania")},
            {"pn", new RegionInfo("Pitcairn","oceania")},
            {"ws", new RegionInfo("Samoa","oceania")},
            {"sb", new RegionInfo("Solomon Islands","oceania")},
            {"tk", new RegionInfo("Tokelau","oceania")},
            {"to", new RegionInfo("Tonga","oceania")},
            {"tv", new RegionInfo("Tuvalu","oceania")},
            {"um", new RegionInfo("United States Minor Outlying Islands","oceania")},
            {"vu", new RegionInfo("Vanuatu","oceania")},
            {"wf", new RegionInfo("Wallis and Futuna","oceania")},
            {"ar", new RegionInfo("Argentina","southamerica")},
            {"bo", new RegionInfo("Bolivia (Plurinational State of)","southamerica")},
            {"br", new RegionInfo(Brazil,"southamerica")},
            {"cl", new RegionInfo("Chile","southamerica")},
            {"co", new RegionInfo("Colombia","southamerica")},
            {"ec", new RegionInfo("Ecuador","southamerica")},
            {"fk", new RegionInfo("Falkland Islands (Malvinas)","southamerica")},
            {"gf", new RegionInfo("French Guiana","southamerica")},
            {"gy", new RegionInfo("Guyana","southamerica")},
            {"py", new RegionInfo("Paraguay","southamerica")},
            {"pe", new RegionInfo("Peru","southamerica")},
            {"gs", new RegionInfo("South Georgia and the South Sandwich Islands","southamerica")},
            {"sr", new RegionInfo("Suriname","southamerica")},
            {"uy", new RegionInfo("Uruguay","southamerica")},
            {"ve", new RegionInfo("Venezuela (Bolivarian Republic of)","southamerica")},
            {"af", new RegionInfo("Africa","world")},
            {"an", new RegionInfo("Antarctica","world")},
            {"as", new RegionInfo(Asia,"world")},
            {"eu", new RegionInfo(Europe,"world")},
            {"na", new RegionInfo(NorthAmerica,"world")},
            {"oc", new RegionInfo(Oceania,"world")},
            {"sa", new RegionInfo(SouthAmerica,"world")},
            {"dza", new RegionInfo("Algeria","africa")},
            {"ago", new RegionInfo("Angola","africa")},
            {"ben", new RegionInfo("Benin","africa")},
            {"bwa", new RegionInfo("Botswana","africa")},
            {"iot", new RegionInfo("British Indian Ocean Territory","africa")},
            {"bfa", new RegionInfo("Burkina Faso","africa")},
            {"bdi", new RegionInfo("Burundi","africa")},
            {"cpv", new RegionInfo("Cabo Verde","africa")},
            {"cmr", new RegionInfo("Cameroon","africa")},
            {"caf", new RegionInfo("Central African Republic","africa")},
            {"tcd", new RegionInfo("Chad","africa")},
            {"com", new RegionInfo("Comoros","africa")},
            {"cog", new RegionInfo("Congo","africa")},
            {"cod", new RegionInfo("Congo, Democratic Republic of the","africa")},
            {"civ", new RegionInfo("Côte d'Ivoire","africa")},
            {"dji", new RegionInfo("Djibouti","africa")},
            {"egy", new RegionInfo("Egypt","africa")},
            {"gnq", new RegionInfo("Equatorial Guinea","africa")},
            {"eri", new RegionInfo("Eritrea","africa")},
            {"swz", new RegionInfo("Eswatini","africa")},
            {"eth", new RegionInfo("Ethiopia","africa")},
            {"atf", new RegionInfo("French Southern Territories","africa")},
            {"gab", new RegionInfo("Gabon","africa")},
            {"gmb", new RegionInfo("Gambia","africa")},
            {"gha", new RegionInfo("Ghana","africa")},
            {"gin", new RegionInfo("Guinea","africa")},
            {"gnb", new RegionInfo("Guinea-Bissau","africa")},
            {"ken", new RegionInfo("Kenya","africa")},
            {"lso", new RegionInfo("Lesotho","africa")},
            {"lbr", new RegionInfo("Liberia","africa")},
            {"lby", new RegionInfo("Libya","africa")},
            {"mdg", new RegionInfo("Madagascar","africa")},
            {"mwi", new RegionInfo("Malawi","africa")},
            {"mli", new RegionInfo("Mali","africa")},
            {"mrt", new RegionInfo("Mauritania","africa")},
            {"mus", new RegionInfo("Mauritius","africa")},
            {"myt", new RegionInfo("Mayotte","africa")},
            {"mar", new RegionInfo("Morocco","africa")},
            {"moz", new RegionInfo("Mozambique","africa")},
            {"nam", new RegionInfo("Namibia","africa")},
            {"ner", new RegionInfo("Niger","africa")},
            {"nga", new RegionInfo("Nigeria","africa")},
            {"reu", new RegionInfo("Réunion","africa")},
            {"rwa", new RegionInfo("Rwanda","africa")},
            {"shn", new RegionInfo("Saint Helena, Ascension and Tristan da Cunha","africa")},
            {"stp", new RegionInfo("Sao Tome and Principe","africa")},
            {"sen", new RegionInfo("Senegal","africa")},
            {"syc", new RegionInfo("Seychelles","africa")},
            {"sle", new RegionInfo("Sierra Leone","africa")},
            {"som", new RegionInfo("Somalia","africa")},
            {"zaf", new RegionInfo("South Africa","africa")},
            {"ssd", new RegionInfo("South Sudan","africa")},
            {"sdn", new RegionInfo("Sudan","africa")},
            {"tza", new RegionInfo("Tanzania, United Republic of","africa")},
            {"tgo", new RegionInfo("Togo","africa")},
            {"tun", new RegionInfo("Tunisia","africa")},
            {"uga", new RegionInfo("Uganda","africa")},
            {"esh", new RegionInfo("Western Sahara","africa")},
            {"zmb", new RegionInfo("Zambia","africa")},
            {"zwe", new RegionInfo("Zimbabwe","africa")},
            {"ata", new RegionInfo("Antarctica","antarctica")},
            {"afg", new RegionInfo("Afghanistan","asia")},
            {"arm", new RegionInfo("Armenia","asia")},
            {"aze", new RegionInfo("Azerbaijan","asia")},
            {"bhr", new RegionInfo("Bahrain","asia")},
            {"bgd", new RegionInfo("Bangladesh","asia")},
            {"btn", new RegionInfo("Bhutan","asia")},
            {"brn", new RegionInfo("Brunei Darussalam","asia")},
            {"khm", new RegionInfo("Cambodia","asia")},
            {"chn", new RegionInfo(China,"asia")},
            {"cyp", new RegionInfo("Cyprus","asia")},
            {"geo", new RegionInfo("Georgia","asia")},
            {"hkg", new RegionInfo(HongKong,"asia")},
            {"ind", new RegionInfo("India","asia")},
            {"idn", new RegionInfo("Indonesia","asia")},
            {"irn", new RegionInfo("Iran (Islamic Republic of)","asia")},
            {"irq", new RegionInfo("Iraq","asia")},
            {"isr", new RegionInfo("Israel","asia")},
            {"jpn", new RegionInfo(Japan,"asia")},
            {"jor", new RegionInfo("Jordan","asia")},
            {"kaz", new RegionInfo("Kazakhstan","asia")},
            {"prk", new RegionInfo(Korea,"asia")},
            {"kor", new RegionInfo(Korea,"asia")},
            {"kwt", new RegionInfo("Kuwait","asia")},
            {"kgz", new RegionInfo("Kyrgyzstan","asia")},
            {"lao", new RegionInfo("Lao People's Democratic Republic","asia")},
            {"lbn", new RegionInfo("Lebanon","asia")},
            {"mac", new RegionInfo("Macao","asia")},
            {"mys", new RegionInfo("Malaysia","asia")},
            {"mdv", new RegionInfo("Maldives","asia")},
            {"mng", new RegionInfo("Mongolia","asia")},
            {"mmr", new RegionInfo("Myanmar","asia")},
            {"npl", new RegionInfo("Nepal","asia")},
            {"omn", new RegionInfo("Oman","asia")},
            {"pak", new RegionInfo("Pakistan","asia")},
            {"pse", new RegionInfo("Palestine, State of","asia")},
            {"phl", new RegionInfo("Philippines","asia")},
            {"qat", new RegionInfo("Qatar","asia")},
            {"sau", new RegionInfo("Saudi Arabia","asia")},
            {"sgp", new RegionInfo("Singapore","asia")},
            {"lka", new RegionInfo("Sri Lanka","asia")},
            {"syr", new RegionInfo("Syrian Arab Republic","asia")},
            {"twn", new RegionInfo("Taiwan, Province of China","asia")},
            {"tjk", new RegionInfo("Tajikistan","asia")},
            {"tha", new RegionInfo(Thailand,"asia")},
            {"tls", new RegionInfo("Timor-Leste","asia")},
            {"tur", new RegionInfo("Turkey","asia")},
            {"tkm", new RegionInfo("Turkmenistan","asia")},
            {"are", new RegionInfo("United Arab Emirates","asia")},
            {"uzb", new RegionInfo("Uzbekistan","asia")},
            {"vnm", new RegionInfo("Viet Nam","asia")},
            {"yem", new RegionInfo("Yemen","asia")},
            {"ala", new RegionInfo("Åland Islands","europe")},
            {"alb", new RegionInfo("Albania","europe")},
            {"and", new RegionInfo("Andorra","europe")},
            {"aut", new RegionInfo("Austria","europe")},
            {"blr", new RegionInfo("Belarus","europe")},
            {"bel", new RegionInfo("Belgium","europe")},
            {"bih", new RegionInfo("Bosnia and Herzegovina","europe")},
            {"bgr", new RegionInfo("Bulgaria","europe")},
            {"hrv", new RegionInfo("Croatia","europe")},
            {"cze", new RegionInfo("Czechia","europe")},
            {"dnk", new RegionInfo("Denmark","europe")},
            {"est", new RegionInfo("Estonia","europe")},
            {"fro", new RegionInfo("Faroe Islands","europe")},
            {"fin", new RegionInfo(Finland,"europe")},
            {"fra", new RegionInfo(France,"europe")},
            {"deu", new RegionInfo(Germany,"europe")},
            {"gib", new RegionInfo("Gibraltar","europe")},
            {"grc", new RegionInfo(Greece,"europe")},
            {"ggy", new RegionInfo("Guernsey","europe")},
            {"vat", new RegionInfo("Holy See","europe")},
            {"hun", new RegionInfo("Hungary","europe")},
            {"isl", new RegionInfo("Iceland","europe")},
            {"irl", new RegionInfo("Ireland","europe")},
            {"imn", new RegionInfo("Isle of Man","europe")},
            {"ita", new RegionInfo(Italy,"europe")},
            {"jey", new RegionInfo("Jersey","europe")},
            {"lva", new RegionInfo("Latvia","europe")},
            {"lie", new RegionInfo("Liechtenstein","europe")},
            {"ltu", new RegionInfo("Lithuania","europe")},
            {"lux", new RegionInfo("Luxembourg","europe")},
            {"mlt", new RegionInfo("Malta","europe")},
            {"mda", new RegionInfo("Moldova, Republic of","europe")},
            {"mco", new RegionInfo("Monaco","europe")},
            {"mne", new RegionInfo("Montenegro","europe")},
            {"nld", new RegionInfo(TheNetherlands,"europe")},
            {"mkd", new RegionInfo("North Macedonia","europe")},
            {"nor", new RegionInfo(Norway,"europe")},
            {"pol", new RegionInfo("Poland","europe")},
            {"prt", new RegionInfo("Portugal","europe")},
            {"rou", new RegionInfo("Romania","europe")},
            {"rus", new RegionInfo(Russia,"europe")},
            {"smr", new RegionInfo("San Marino","europe")},
            {"srb", new RegionInfo("Serbia","europe")},
            {"svk", new RegionInfo("Slovakia","europe")},
            {"svn", new RegionInfo("Slovenia","europe")},
            {"esp", new RegionInfo(Spain,"europe")},
            {"sjm", new RegionInfo("Svalbard and Jan Mayen","europe")},
            {"swe", new RegionInfo(Sweden,"europe")},
            {"che", new RegionInfo("Switzerland","europe")},
            {"ukr", new RegionInfo("Ukraine","europe")},
            {"gbr", new RegionInfo(UnitedKingdom,"europe")},
            {"vgb", new RegionInfo("Virgin Islands (British)","northamerica")},
            {"aia", new RegionInfo("Anguilla","northamerica")},
            {"atg", new RegionInfo("Antigua and Barbuda","northamerica")},
            {"abw", new RegionInfo("Aruba","northamerica")},
            {"bhs", new RegionInfo("Bahamas","northamerica")},
            {"brb", new RegionInfo("Barbados","northamerica")},
            {"blz", new RegionInfo("Belize","northamerica")},
            {"bmu", new RegionInfo("Bermuda","northamerica")},
            {"bes", new RegionInfo("Bonaire, Sint Eustatius and Saba","northamerica")},
            {"can", new RegionInfo(Canada,"northamerica")},
            {"cym", new RegionInfo("Cayman Islands","northamerica")},
            {"cri", new RegionInfo("Costa Rica","northamerica")},
            {"cub", new RegionInfo("Cuba","northamerica")},
            {"cuw", new RegionInfo("Curaçao","northamerica")},
            {"dma", new RegionInfo("Dominica","northamerica")},
            {"dom", new RegionInfo("Dominican Republic","northamerica")},
            {"slv", new RegionInfo("El Salvador","northamerica")},
            {"grl", new RegionInfo("Greenland","northamerica")},
            {"grd", new RegionInfo("Grenada","northamerica")},
            {"glp", new RegionInfo("Guadeloupe","northamerica")},
            {"gtm", new RegionInfo("Guatemala","northamerica")},
            {"hti", new RegionInfo("Haiti","northamerica")},
            {"hnd", new RegionInfo("Honduras","northamerica")},
            {"jam", new RegionInfo("Jamaica","northamerica")},
            {"mtq", new RegionInfo("Martinique","northamerica")},
            {"mex", new RegionInfo("Mexico","northamerica")},
            {"msr", new RegionInfo("Montserrat","northamerica")},
            {"nic", new RegionInfo("Nicaragua","northamerica")},
            {"pan", new RegionInfo("Panama","northamerica")},
            {"pri", new RegionInfo("Puerto Rico","northamerica")},
            {"blm", new RegionInfo("Saint Barthélemy","northamerica")},
            {"kna", new RegionInfo("Saint Kitts and Nevis","northamerica")},
            {"lca", new RegionInfo("Saint Lucia","northamerica")},
            {"maf", new RegionInfo("Saint Martin (French part)","northamerica")},
            {"spm", new RegionInfo("Saint Pierre and Miquelon","northamerica")},
            {"vct", new RegionInfo("Saint Vincent and the Grenadines","northamerica")},
            {"sxm", new RegionInfo("Sint Maarten (Dutch part)","northamerica")},
            {"tto", new RegionInfo("Trinidad and Tobago","northamerica")},
            {"tca", new RegionInfo("Turks and Caicos Islands","northamerica")},
            {"usa", new RegionInfo(UnitedStates,"northamerica")},
            {"vir", new RegionInfo("Virgin Islands (U.S.)","northamerica")},
            {"asm", new RegionInfo("American Samoa","oceania")},
            {"aus", new RegionInfo(Australia,"oceania")},
            {"cxr", new RegionInfo("Christmas Island","oceania")},
            {"cck", new RegionInfo("Cocos (Keeling) Islands","oceania")},
            {"cok", new RegionInfo("Cook Islands","oceania")},
            {"fji", new RegionInfo("Fiji","oceania")},
            {"pyf", new RegionInfo("French Polynesia","oceania")},
            {"gum", new RegionInfo("Guam","oceania")},
            {"hmd", new RegionInfo("Heard Island and McDonald Islands","oceania")},
            {"kir", new RegionInfo("Kiribati","oceania")},
            {"mhl", new RegionInfo("Marshall Islands","oceania")},
            {"fsm", new RegionInfo("Micronesia (Federated States of)","oceania")},
            {"nru", new RegionInfo("Nauru","oceania")},
            {"ncl", new RegionInfo("New Caledonia","oceania")},
            {"nzl", new RegionInfo("New Zealand","oceania")},
            {"niu", new RegionInfo("Niue","oceania")},
            {"nfk", new RegionInfo("Norfolk Island","oceania")},
            {"mnp", new RegionInfo("Northern Mariana Islands","oceania")},
            {"plw", new RegionInfo("Palau","oceania")},
            {"png", new RegionInfo("Papua New Guinea","oceania")},
            {"pcn", new RegionInfo("Pitcairn","oceania")},
            {"wsm", new RegionInfo("Samoa","oceania")},
            {"slb", new RegionInfo("Solomon Islands","oceania")},
            {"tkl", new RegionInfo("Tokelau","oceania")},
            {"ton", new RegionInfo("Tonga","oceania")},
            {"tuv", new RegionInfo("Tuvalu","oceania")},
            {"umi", new RegionInfo("United States Minor Outlying Islands","oceania")},
            {"vut", new RegionInfo("Vanuatu","oceania")},
            {"wlf", new RegionInfo("Wallis and Futuna","oceania")},
            {"arg", new RegionInfo("Argentina","southamerica")},
            {"bol", new RegionInfo("Bolivia (Plurinational State of)","southamerica")},
            {"bra", new RegionInfo(Brazil,"southamerica")},
            {"chl", new RegionInfo("Chile","southamerica")},
            {"col", new RegionInfo("Colombia","southamerica")},
            {"ecu", new RegionInfo("Ecuador","southamerica")},
            {"flk", new RegionInfo("Falkland Islands (Malvinas)","southamerica")},
            {"guf", new RegionInfo("French Guiana","southamerica")},
            {"guy", new RegionInfo("Guyana","southamerica")},
            {"pry", new RegionInfo("Paraguay","southamerica")},
            {"per", new RegionInfo("Peru","southamerica")},
            {"sgs", new RegionInfo("South Georgia and the South Sandwich Islands","southamerica")},
            {"sur", new RegionInfo("Suriname","southamerica")},
            {"ury", new RegionInfo("Uruguay","southamerica")},
            {"ven", new RegionInfo("Venezuela (Bolivarian Republic of)","southamerica")},
            {"algeria", new RegionInfo("Algeria","africa")},
            {"angola", new RegionInfo("Angola","africa")},
            {"benin", new RegionInfo("Benin","africa")},
            {"botswana", new RegionInfo("Botswana","africa")},
            {"britishindianoceanterritory", new RegionInfo("British Indian Ocean Territory","africa")},
            {"burkinafaso", new RegionInfo("Burkina Faso","africa")},
            {"burundi", new RegionInfo("Burundi","africa")},
            {"caboverde", new RegionInfo("Cabo Verde","africa")},
            {"cameroon", new RegionInfo("Cameroon","africa")},
            {"centralafricanrepublic", new RegionInfo("Central African Republic","africa")},
            {"chad", new RegionInfo("Chad","africa")},
            {"comoros", new RegionInfo("Comoros","africa")},
            {"congo", new RegionInfo("Congo","africa")},
            {"congodemocraticrepublicof", new RegionInfo("Congo, Democratic Republic of the","africa")},
            {"ctedivoire", new RegionInfo("Côte d'Ivoire","africa")},
            {"djibouti", new RegionInfo("Djibouti","africa")},
            {"egypt", new RegionInfo("Egypt","africa")},
            {"equatorialguinea", new RegionInfo("Equatorial Guinea","africa")},
            {"eritrea", new RegionInfo("Eritrea","africa")},
            {"eswatini", new RegionInfo("Eswatini","africa")},
            {"ethiopia", new RegionInfo("Ethiopia","africa")},
            {"frenchsouthernterritories", new RegionInfo("French Southern Territories","africa")},
            {"gabon", new RegionInfo("Gabon","africa")},
            {"gambia", new RegionInfo("Gambia","africa")},
            {"ghana", new RegionInfo("Ghana","africa")},
            {"guinea", new RegionInfo("Guinea","africa")},
            {"guineabissau", new RegionInfo("Guinea-Bissau","africa")},
            {"kenya", new RegionInfo("Kenya","africa")},
            {"lesotho", new RegionInfo("Lesotho","africa")},
            {"liberia", new RegionInfo("Liberia","africa")},
            {"libya", new RegionInfo("Libya","africa")},
            {"madagascar", new RegionInfo("Madagascar","africa")},
            {"malawi", new RegionInfo("Malawi","africa")},
            {"mali", new RegionInfo("Mali","africa")},
            {"mauritania", new RegionInfo("Mauritania","africa")},
            {"mauritius", new RegionInfo("Mauritius","africa")},
            {"mayotte", new RegionInfo("Mayotte","africa")},
            {"morocco", new RegionInfo("Morocco","africa")},
            {"mozambique", new RegionInfo("Mozambique","africa")},
            {"namibia", new RegionInfo("Namibia","africa")},
            {"niger", new RegionInfo("Niger","africa")},
            {"nigeria", new RegionInfo("Nigeria","africa")},
            {"runion", new RegionInfo("Réunion","africa")},
            {"rwanda", new RegionInfo("Rwanda","africa")},
            {"sainthelenaascensionandtristandacunha", new RegionInfo("Saint Helena, Ascension and Tristan da Cunha","africa")},
            {"saotomeandprincipe", new RegionInfo("Sao Tome and Principe","africa")},
            {"senegal", new RegionInfo("Senegal","africa")},
            {"seychelles", new RegionInfo("Seychelles","africa")},
            {"sierraleone", new RegionInfo("Sierra Leone","africa")},
            {"somalia", new RegionInfo("Somalia","africa")},
            {"southafrica", new RegionInfo("South Africa","africa")},
            {"southsudan", new RegionInfo("South Sudan","africa")},
            {"sudan", new RegionInfo("Sudan","africa")},
            {"tanzaniaunitedrepublicof", new RegionInfo("Tanzania, United Republic of","africa")},
            {"togo", new RegionInfo("Togo","africa")},
            {"tunisia", new RegionInfo("Tunisia","africa")},
            {"uganda", new RegionInfo("Uganda","africa")},
            {"westernsahara", new RegionInfo("Western Sahara","africa")},
            {"zambia", new RegionInfo("Zambia","africa")},
            {"zimbabwe", new RegionInfo("Zimbabwe","africa")},
            {"afghanistan", new RegionInfo("Afghanistan","asia")},
            {"armenia", new RegionInfo("Armenia","asia")},
            {"azerbaijan", new RegionInfo("Azerbaijan","asia")},
            {"bahrain", new RegionInfo("Bahrain","asia")},
            {"bangladesh", new RegionInfo("Bangladesh","asia")},
            {"bhutan", new RegionInfo("Bhutan","asia")},
            {"bruneidarussalam", new RegionInfo("Brunei Darussalam","asia")},
            {"cambodia", new RegionInfo("Cambodia","asia")},
            {"china", new RegionInfo(China,"asia")},
            {"cyprus", new RegionInfo("Cyprus","asia")},
            {"georgia", new RegionInfo("Georgia","asia")},
            {"hongkong", new RegionInfo(HongKong,"asia")},
            {"india", new RegionInfo("India","asia")},
            {"indonesia", new RegionInfo("Indonesia","asia")},
            {"iranislamicrepublicof", new RegionInfo("Iran (Islamic Republic of)","asia")},
            {"iraq", new RegionInfo("Iraq","asia")},
            {"israel", new RegionInfo("Israel","asia")},
            {"japan", new RegionInfo(Japan,"asia")},
            {"jordan", new RegionInfo("Jordan","asia")},
            {"kazakhstan", new RegionInfo("Kazakhstan","asia")},
            {"koreademocraticpeoplesrepublicof", new RegionInfo(Korea,"asia")},
            {"korearepublicof", new RegionInfo(Korea,"asia")},
            {"kuwait", new RegionInfo("Kuwait","asia")},
            {"kyrgyzstan", new RegionInfo("Kyrgyzstan","asia")},
            {"laopeoplesdemocraticrepublic", new RegionInfo("Lao People's Democratic Republic","asia")},
            {"lebanon", new RegionInfo("Lebanon","asia")},
            {"macao", new RegionInfo("Macao","asia")},
            {"malaysia", new RegionInfo("Malaysia","asia")},
            {"maldives", new RegionInfo("Maldives","asia")},
            {"mongolia", new RegionInfo("Mongolia","asia")},
            {"myanmar", new RegionInfo("Myanmar","asia")},
            {"nepal", new RegionInfo("Nepal","asia")},
            {"oman", new RegionInfo("Oman","asia")},
            {"pakistan", new RegionInfo("Pakistan","asia")},
            {"palestinestateof", new RegionInfo("Palestine, State of","asia")},
            {"philippines", new RegionInfo("Philippines","asia")},
            {"qatar", new RegionInfo("Qatar","asia")},
            {"saudiarabia", new RegionInfo("Saudi Arabia","asia")},
            {"singapore", new RegionInfo("Singapore","asia")},
            {"srilanka", new RegionInfo("Sri Lanka","asia")},
            {"syrianarabrepublic", new RegionInfo("Syrian Arab Republic","asia")},
            {"taiwanprovinceofchina", new RegionInfo("Taiwan, Province of China","asia")},
            {"tajikistan", new RegionInfo("Tajikistan","asia")},
            {"thailand", new RegionInfo(Thailand,"asia")},
            {"timorleste", new RegionInfo("Timor-Leste","asia")},
            {"turkey", new RegionInfo("Turkey","asia")},
            {"turkmenistan", new RegionInfo("Turkmenistan","asia")},
            {"unitedarabemirates", new RegionInfo("United Arab Emirates","asia")},
            {"uzbekistan", new RegionInfo("Uzbekistan","asia")},
            {"vietnam", new RegionInfo("Viet Nam","asia")},
            {"yemen", new RegionInfo("Yemen","asia")},
            {"landislands", new RegionInfo("Åland Islands","europe")},
            {"albania", new RegionInfo("Albania","europe")},
            {"andorra", new RegionInfo("Andorra","europe")},
            {"austria", new RegionInfo("Austria","europe")},
            {"belarus", new RegionInfo("Belarus","europe")},
            {"belgium", new RegionInfo("Belgium","europe")},
            {"bosniaandherzegovina", new RegionInfo("Bosnia and Herzegovina","europe")},
            {"bulgaria", new RegionInfo("Bulgaria","europe")},
            {"croatia", new RegionInfo("Croatia","europe")},
            {"czechia", new RegionInfo("Czechia","europe")},
            {"denmark", new RegionInfo("Denmark","europe")},
            {"estonia", new RegionInfo("Estonia","europe")},
            {"faroeislands", new RegionInfo("Faroe Islands","europe")},
            {"finland", new RegionInfo(Finland,"europe")},
            {"france", new RegionInfo(France,"europe")},
            {"germany", new RegionInfo(Germany,"europe")},
            {"gibraltar", new RegionInfo("Gibraltar","europe")},
            {"greece", new RegionInfo(Greece,"europe")},
            {"guernsey", new RegionInfo("Guernsey","europe")},
            {"holysee", new RegionInfo("Holy See","europe")},
            {"hungary", new RegionInfo("Hungary","europe")},
            {"iceland", new RegionInfo("Iceland","europe")},
            {"ireland", new RegionInfo("Ireland","europe")},
            {"isleofman", new RegionInfo("Isle of Man","europe")},
            {"italy", new RegionInfo(Italy,"europe")},
            {"jersey", new RegionInfo("Jersey","europe")},
            {"latvia", new RegionInfo("Latvia","europe")},
            {"liechtenstein", new RegionInfo("Liechtenstein","europe")},
            {"lithuania", new RegionInfo("Lithuania","europe")},
            {"luxembourg", new RegionInfo("Luxembourg","europe")},
            {"malta", new RegionInfo("Malta","europe")},
            {"moldovarepublicof", new RegionInfo("Moldova, Republic of","europe")},
            {"monaco", new RegionInfo("Monaco","europe")},
            {"montenegro", new RegionInfo("Montenegro","europe")},
            {"netherlands", new RegionInfo(TheNetherlands,"europe")},
            {"northmacedonia", new RegionInfo("North Macedonia","europe")},
            {"norway", new RegionInfo(Norway,"europe")},
            {"poland", new RegionInfo("Poland","europe")},
            {"portugal", new RegionInfo("Portugal","europe")},
            {"romania", new RegionInfo("Romania","europe")},
            {"russianfederation", new RegionInfo(Russia,"europe")},
            {"sanmarino", new RegionInfo("San Marino","europe")},
            {"serbia", new RegionInfo("Serbia","europe")},
            {"slovakia", new RegionInfo("Slovakia","europe")},
            {"slovenia", new RegionInfo("Slovenia","europe")},
            {"spain", new RegionInfo(Spain,"europe")},
            {"svalbardandjanmayen", new RegionInfo("Svalbard and Jan Mayen","europe")},
            {"sweden", new RegionInfo(Sweden,"europe")},
            {"switzerland", new RegionInfo("Switzerland","europe")},
            {"ukraine", new RegionInfo("Ukraine","europe")},
            {"unitedkingdomofgreatbritainandnorthernireland", new RegionInfo(UnitedKingdom,"europe")},
            {"virginislandsbritish", new RegionInfo("Virgin Islands (British)","northamerica")},
            {"anguilla", new RegionInfo("Anguilla","northamerica")},
            {"antiguaandbarbuda", new RegionInfo("Antigua and Barbuda","northamerica")},
            {"aruba", new RegionInfo("Aruba","northamerica")},
            {"bahamas", new RegionInfo("Bahamas","northamerica")},
            {"barbados", new RegionInfo("Barbados","northamerica")},
            {"belize", new RegionInfo("Belize","northamerica")},
            {"bermuda", new RegionInfo("Bermuda","northamerica")},
            {"bonairesinteustatiusandsaba", new RegionInfo("Bonaire, Sint Eustatius and Saba","northamerica")},
            {"canada", new RegionInfo(Canada,"northamerica")},
            {"caymanislands", new RegionInfo("Cayman Islands","northamerica")},
            {"costarica", new RegionInfo("Costa Rica","northamerica")},
            {"cuba", new RegionInfo("Cuba","northamerica")},
            {"curaao", new RegionInfo("Curaçao","northamerica")},
            {"dominica", new RegionInfo("Dominica","northamerica")},
            {"dominicanrepublic", new RegionInfo("Dominican Republic","northamerica")},
            {"elsalvador", new RegionInfo("El Salvador","northamerica")},
            {"greenland", new RegionInfo("Greenland","northamerica")},
            {"grenada", new RegionInfo("Grenada","northamerica")},
            {"guadeloupe", new RegionInfo("Guadeloupe","northamerica")},
            {"guatemala", new RegionInfo("Guatemala","northamerica")},
            {"haiti", new RegionInfo("Haiti","northamerica")},
            {"honduras", new RegionInfo("Honduras","northamerica")},
            {"jamaica", new RegionInfo("Jamaica","northamerica")},
            {"martinique", new RegionInfo("Martinique","northamerica")},
            {"mexico", new RegionInfo("Mexico","northamerica")},
            {"montserrat", new RegionInfo("Montserrat","northamerica")},
            {"nicaragua", new RegionInfo("Nicaragua","northamerica")},
            {"panama", new RegionInfo("Panama","northamerica")},
            {"puertorico", new RegionInfo("Puerto Rico","northamerica")},
            {"saintbarthlemy", new RegionInfo("Saint Barthélemy","northamerica")},
            {"saintkittsandnevis", new RegionInfo("Saint Kitts and Nevis","northamerica")},
            {"saintlucia", new RegionInfo("Saint Lucia","northamerica")},
            {"saintmartinfrenchpart", new RegionInfo("Saint Martin (French part)","northamerica")},
            {"saintpierreandmiquelon", new RegionInfo("Saint Pierre and Miquelon","northamerica")},
            {"saintvincentandgrenadines", new RegionInfo("Saint Vincent and the Grenadines","northamerica")},
            {"sintmaartendutchpart", new RegionInfo("Sint Maarten (Dutch part)","northamerica")},
            {"trinidadandtobago", new RegionInfo("Trinidad and Tobago","northamerica")},
            {"turksandcaicosislands", new RegionInfo("Turks and Caicos Islands","northamerica")},
            {"unitedstatesofamerica", new RegionInfo(UnitedStates,"northamerica")},
            {"virginislandsus", new RegionInfo("Virgin Islands (U.S.)","northamerica")},
            {"americansamoa", new RegionInfo("American Samoa","oceania")},
            {"australia", new RegionInfo(Australia,"oceania")},
            {"christmasisland", new RegionInfo("Christmas Island","oceania")},
            {"cocoskeelingislands", new RegionInfo("Cocos (Keeling) Islands","oceania")},
            {"cookislands", new RegionInfo("Cook Islands","oceania")},
            {"fiji", new RegionInfo("Fiji","oceania")},
            {"frenchpolynesia", new RegionInfo("French Polynesia","oceania")},
            {"guam", new RegionInfo("Guam","oceania")},
            {"heardislandandmcdonaldislands", new RegionInfo("Heard Island and McDonald Islands","oceania")},
            {"kiribati", new RegionInfo("Kiribati","oceania")},
            {"marshallislands", new RegionInfo("Marshall Islands","oceania")},
            {"micronesiafederatedstatesof", new RegionInfo("Micronesia (Federated States of)","oceania")},
            {"nauru", new RegionInfo("Nauru","oceania")},
            {"newcaledonia", new RegionInfo("New Caledonia","oceania")},
            {"newzealand", new RegionInfo("New Zealand","oceania")},
            {"niue", new RegionInfo("Niue","oceania")},
            {"norfolkisland", new RegionInfo("Norfolk Island","oceania")},
            {"northernmarianaislands", new RegionInfo("Northern Mariana Islands","oceania")},
            {"palau", new RegionInfo("Palau","oceania")},
            {"papuanewguinea", new RegionInfo("Papua New Guinea","oceania")},
            {"pitcairn", new RegionInfo("Pitcairn","oceania")},
            {"samoa", new RegionInfo("Samoa","oceania")},
            {"solomonislands", new RegionInfo("Solomon Islands","oceania")},
            {"tokelau", new RegionInfo("Tokelau","oceania")},
            {"tonga", new RegionInfo("Tonga","oceania")},
            {"tuvalu", new RegionInfo("Tuvalu","oceania")},
            {"unitedstatesminoroutlyingislands", new RegionInfo("United States Minor Outlying Islands","oceania")},
            {"vanuatu", new RegionInfo("Vanuatu","oceania")},
            {"wallisandfutuna", new RegionInfo("Wallis and Futuna","oceania")},
            {"argentina", new RegionInfo("Argentina","southamerica")},
            {"boliviaplurinationalstateof", new RegionInfo("Bolivia (Plurinational State of)","southamerica")},
            {"brazil", new RegionInfo(Brazil,"southamerica")},
            {"chile", new RegionInfo("Chile","southamerica")},
            {"colombia", new RegionInfo("Colombia","southamerica")},
            {"ecuador", new RegionInfo("Ecuador","southamerica")},
            {"falklandislandsmalvinas", new RegionInfo("Falkland Islands (Malvinas)","southamerica")},
            {"frenchguiana", new RegionInfo("French Guiana","southamerica")},
            {"guyana", new RegionInfo("Guyana","southamerica")},
            {"paraguay", new RegionInfo("Paraguay","southamerica")},
            {"peru", new RegionInfo("Peru","southamerica")},
            {"southgeorgiaandsouthsandwichislands", new RegionInfo("South Georgia and the South Sandwich Islands","southamerica")},
            {"suriname", new RegionInfo("Suriname","southamerica")},
            {"uruguay", new RegionInfo("Uruguay","southamerica")},
            {"venezuelabolivarianrepublicof", new RegionInfo("Venezuela (Bolivarian Republic of)","southamerica")},
            {"africa", new RegionInfo("Africa","world")},
            {"antarctica", new RegionInfo("Antarctica","world")},
            {"asia", new RegionInfo(Asia,"world")},
            {"europe", new RegionInfo(Europe,"world")},
            {"northamerica", new RegionInfo(NorthAmerica,"world")},
            {"oceania", new RegionInfo(Oceania,"world")},
            {"southamerica", new RegionInfo(SouthAmerica,"world")},
            {"world", new RegionInfo(World,None)}

        };
    }
}