// <auto-generated />
using LBGDBMetadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClassLibrary1.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20191230061937_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("LBGDBMetadata.Metadata.Game", b =>
                {
                    b.Property<string>("DatabaseID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityRatingCount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cooperative")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ESRB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxPlayers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("WikipediaURL")
                        .HasColumnType("TEXT");

                    b.HasKey("DatabaseID");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
